#!/usr/bin/env node
/**
 * Regenerates src/environments/environment.ts from environment variables.
 *
 * FRONTEND_IMPROVEMENT_PLAN.md task 4.1.7. Firebase web config is public by design — it
 * ships in the bundle either way — so this is hygiene, not secrecy: the point is that
 * pointing a build at a different Firebase project or API host stops being a code change.
 *
 * Deliberately opt-in. If FIREBASE_API_KEY is unset the script does nothing and leaves the
 * committed file alone, so local development and `npm ci && npm run build` keep working
 * with no extra setup. A deploy pipeline exports the variables and runs it before building.
 *
 *   FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET,
 *   FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID, FIREBASE_MEASUREMENT_ID, API_URL
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const target = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../src/environments/environment.ts'
);

if (!process.env.FIREBASE_API_KEY) {
  console.log('[generate-env] FIREBASE_API_KEY not set — keeping the committed environment.ts');
  process.exit(0);
}

const value = (name, fallback = '') => process.env[name] ?? fallback;

const contents = `/**
 * GENERATED by scripts/generate-env.mjs — do not edit by hand.
 * Regenerate with \`npm run config:env\` after exporting the FIREBASE_* variables.
 */
export const environment = {
  production: true,
  apiUrl: '${value('API_URL', 'http://localhost:3000')}',
  firebaseConfig: {
    apiKey: '${value('FIREBASE_API_KEY')}',
    authDomain: '${value('FIREBASE_AUTH_DOMAIN')}',
    projectId: '${value('FIREBASE_PROJECT_ID')}',
    storageBucket: '${value('FIREBASE_STORAGE_BUCKET')}',
    messagingSenderId: '${value('FIREBASE_MESSAGING_SENDER_ID')}',
    appId: '${value('FIREBASE_APP_ID')}',
    measurementId: '${value('FIREBASE_MEASUREMENT_ID')}',
  },
};
`;

writeFileSync(target, contents);
console.log(`[generate-env] wrote ${target} for project ${value('FIREBASE_PROJECT_ID')}`);
